version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edulampung-laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8002:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - DB_HOST=host.containers.internal
      - DB_PORT=3307
      - DB_DATABASE=edulampung
      - DB_USERNAME=root
      - DB_PASSWORD=root